[package]
name = "pez-solochain-template-runtime"
description = "A solochain runtime template built with Bizinikiwi, part of Pezkuwi Sdk."
version = "0.0.0"
license = "Unlicense"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false
documentation = "https://docs.rs/pez-solochain-template-runtime"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true }
scale-info = { features = ["derive", "serde"], workspace = true }
serde_json = { workspace = true, default-features = false, features = [
	"alloc",
] }

# pezframe
pezframe-executive = { workspace = true }
pezframe-metadata-hash-extension = { workspace = true }
pezframe-support = { features = ["experimental"], workspace = true }
pezframe-system = { workspace = true }
pezframe-try-runtime = { optional = true, workspace = true }

# pezframe pallets
pezpallet-aura = { workspace = true }
pezpallet-balances = { workspace = true }
pezpallet-grandpa = { workspace = true }
pezpallet-sudo = { workspace = true }
pezpallet-timestamp = { workspace = true }
pezpallet-transaction-payment = { workspace = true }

# primitives
pezsp-api = { workspace = true }
pezsp-block-builder = { workspace = true }
pezsp-consensus-aura = { features = ["serde"], workspace = true }
pezsp-consensus-grandpa = { features = ["serde"], workspace = true }
pezsp-core = { features = ["serde"], workspace = true }
pezsp-genesis-builder = { workspace = true }
pezsp-inherents = { workspace = true }
pezsp-keyring = { workspace = true }
pezsp-offchain = { workspace = true }
pezsp-runtime = { features = ["serde"], workspace = true }
pezsp-session = { workspace = true }
pezsp-storage = { workspace = true }
pezsp-transaction-pool = { workspace = true }
pezsp-version = { features = ["serde"], workspace = true }

# RPC related
pezframe-system-rpc-runtime-api = { workspace = true }
pezpallet-transaction-payment-rpc-runtime-api = { workspace = true }

# Used for runtime benchmarking
pezframe-benchmarking = { optional = true, workspace = true }
pezframe-system-benchmarking = { optional = true, workspace = true }

# The pezpallet in this template.
pezpallet-template = { workspace = true }

[build-dependencies]
bizinikiwi-wasm-builder = { optional = true, workspace = true, default-features = true }

[features]
default = ["std"]
std = [
	"bizinikiwi-wasm-builder",
	"codec/std",
	"pezframe-benchmarking?/std",
	"pezframe-executive/std",
	"pezframe-metadata-hash-extension/std",
	"pezframe-support/std",
	"pezframe-system-benchmarking?/std",
	"pezframe-system-rpc-runtime-api/std",
	"pezframe-system/std",
	"pezframe-try-runtime?/std",
	"pezpallet-aura/std",
	"pezpallet-balances/std",
	"pezpallet-grandpa/std",
	"pezpallet-sudo/std",
	"pezpallet-template/std",
	"pezpallet-timestamp/std",
	"pezpallet-transaction-payment-rpc-runtime-api/std",
	"pezpallet-transaction-payment/std",
	"pezsp-api/std",
	"pezsp-block-builder/std",
	"pezsp-consensus-aura/std",
	"pezsp-consensus-grandpa/std",
	"pezsp-core/std",
	"pezsp-genesis-builder/std",
	"pezsp-inherents/std",
	"pezsp-keyring/std",
	"pezsp-offchain/std",
	"pezsp-runtime/std",
	"pezsp-session/std",
	"pezsp-storage/std",
	"pezsp-transaction-pool/std",
	"pezsp-version/std",
	"scale-info/std",
	"serde_json/std",
]
runtime-benchmarks = [
	"bizinikiwi-wasm-builder?/runtime-benchmarks",
	"pezframe-benchmarking/runtime-benchmarks",
	"pezframe-executive/runtime-benchmarks",
	"pezframe-metadata-hash-extension/runtime-benchmarks",
	"pezframe-support/runtime-benchmarks",
	"pezframe-system-benchmarking/runtime-benchmarks",
	"pezframe-system-rpc-runtime-api/runtime-benchmarks",
	"pezframe-system/runtime-benchmarks",
	"pezframe-try-runtime?/runtime-benchmarks",
	"pezpallet-aura/runtime-benchmarks",
	"pezpallet-balances/runtime-benchmarks",
	"pezpallet-grandpa/runtime-benchmarks",
	"pezpallet-sudo/runtime-benchmarks",
	"pezpallet-template/runtime-benchmarks",
	"pezpallet-timestamp/runtime-benchmarks",
	"pezpallet-transaction-payment-rpc-runtime-api/runtime-benchmarks",
	"pezpallet-transaction-payment/runtime-benchmarks",
	"pezsp-api/runtime-benchmarks",
	"pezsp-block-builder/runtime-benchmarks",
	"pezsp-consensus-aura/runtime-benchmarks",
	"pezsp-consensus-grandpa/runtime-benchmarks",
	"pezsp-genesis-builder/runtime-benchmarks",
	"pezsp-inherents/runtime-benchmarks",
	"pezsp-keyring/runtime-benchmarks",
	"pezsp-offchain/runtime-benchmarks",
	"pezsp-runtime/runtime-benchmarks",
	"pezsp-session/runtime-benchmarks",
	"pezsp-transaction-pool/runtime-benchmarks",
	"pezsp-version/runtime-benchmarks",
]
try-runtime = [
	"pezframe-executive/try-runtime",
	"pezframe-support/try-runtime",
	"pezframe-system/try-runtime",
	"pezframe-try-runtime/try-runtime",
	"pezpallet-aura/try-runtime",
	"pezpallet-balances/try-runtime",
	"pezpallet-grandpa/try-runtime",
	"pezpallet-sudo/try-runtime",
	"pezpallet-template/try-runtime",
	"pezpallet-timestamp/try-runtime",
	"pezpallet-transaction-payment/try-runtime",
	"pezsp-runtime/try-runtime",
]

# Enable the metadata hash generation.
#
# This is hidden behind a feature because it increases the compile time.
# The wasm binary needs to be compiled twice, once to fetch the metadata,
# generate the metadata hash and then a second time with the
# `RUNTIME_METADATA_HASH` environment variable set for the `CheckMetadataHash`
# extension.
metadata-hash = ["bizinikiwi-wasm-builder/metadata-hash"]

# A convenience feature for enabling things when doing a build
# for an on-chain release.
on-chain-release-build = ["metadata-hash", "pezsp-api/disable-logging"]
