[package]
name = "pezpallet-template"
description = "FRAME pezpallet template for defining custom runtime logic."
version = "0.0.0"
license = "Unlicense"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false
documentation = "https://docs.rs/pezpallet-template"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true }
scale-info = { features = ["derive"], workspace = true }

# frame deps
pezframe-benchmarking = { optional = true, workspace = true }
pezframe-support = { workspace = true }
pezframe-system = { workspace = true }

[dev-dependencies]
pezsp-core = { workspace = true, default-features = true }
pezsp-io = { workspace = true, default-features = true }
pezsp-runtime = { workspace = true, default-features = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"pezframe-benchmarking?/std",
	"pezframe-support/std",
	"pezframe-system/std",
	"pezsp-core/std",
	"pezsp-io/std",
	"pezsp-runtime/std",
	"scale-info/std",
]
runtime-benchmarks = [
	"pezframe-benchmarking/runtime-benchmarks",
	"pezframe-support/runtime-benchmarks",
	"pezframe-system/runtime-benchmarks",
	"pezsp-io/runtime-benchmarks",
	"pezsp-runtime/runtime-benchmarks",
]
try-runtime = [
	"pezframe-support/try-runtime",
	"pezframe-system/try-runtime",
	"pezsp-runtime/try-runtime",
]
